/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountList: typeof import('./src/components/background/AccountList/AccountList.vue')['default']
    Avatar: typeof import('./src/components/common/avatar.vue')['default']
    Calendar: typeof import('./src/components/common/calendar.vue')['default']
    Content: typeof import('./src/components/background/layout/content/content.vue')['default']
    Cropper: typeof import('./src/components/background/Cropper/Cropper.vue')['default']
    DataTable: typeof import('./src/components/background/table/DataTable.vue')['default']
    EditorForm: typeof import('./src/components/background/EditorForm/EditorForm.vue')['default']
    Footer: typeof import('./src/components/background/layout/footer/footer.vue')['default']
    Header: typeof import('./src/components/background/layout/header/header.vue')['default']
    Logo: typeof import('./src/components/background/layout/menu/logo.vue')['default']
    Menu: typeof import('./src/components/common/menu.vue')['default']
    Message: typeof import('./src/components/background/message/message.vue')['default']
    Passwordstrong: typeof import('./src/components/home/passwordstrong.vue')['default']
    Rolemodal: typeof import('./src/components/background/modal/rolemodal.vue')['default']
    Roletree: typeof import('./src/components/background/modal/roletree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityCenter: typeof import('./src/components/background/SecurityCenter/SecurityCenter.vue')['default']
    SecurityLog: typeof import('./src/components/background/SecurityLog/SecurityLog.vue')['default']
    Tabs: typeof import('./src/components/background/layout/header/tabs.vue')['default']
    Upload: typeof import('./src/components/background/upload/upload.vue')['default']
    Userform: typeof import('./src/components/background/userform/userform.vue')['default']
    WangEditor: typeof import('./src/components/background/richtext/WangEditor.vue')['default']
  }
}
